package org.millstone.base.ui;

import org.millstone.base.data.BufferedValidatable;
import org.millstone.base.data.Property;
import org.millstone.base.ui.Component.Focusable;

/**
 * @author Sami Ekblad
 *
 */
public interface Field
	extends
		Component,
		BufferedValidatable,
		Property,
		Property.ValueChangeNotifier,
		Property.ValueChangeListener,
		Property.Editor,
		Focusable {

	void setCaption(String caption);

	String getDescription();
	
	void setDescription(String caption);

	/** Is this field required.
	 * 
	 * Required fields must filled by the user.
	 * 
	 * @return true if the
	 * @since 3.1 
	 */
	public boolean isRequired();

	/** Set the field required.
	 * Required fields must filled by the user.
	 * 
	 * @param required Is the field required
	 * @since 3.1 
	 */
	public void setRequired(boolean required);

	/** An <code>Event</code> object specifying the Field whose value
	 * has been changed.
	 * @author IT Mill Ltd.
		 * @version @VERSION@
		 * @since 3.0
	 */
	public class ValueChangeEvent
		extends Component.Event
		implements Property.ValueChangeEvent {

		/**
         * Serial generated by eclipse.
         */
        private static final long serialVersionUID = 3545803169444672816L;

        /** Constructs a new event object with the specified source
		 * field object.
		 *
		 * @param source the field that caused the event
		 */
		public ValueChangeEvent(Field source) {
			super(source);
		}

		/** Gets the Property which triggered the event.
		 *
		 * @return Source Property of the event.
		 */
		public Property getProperty() {
			return (Property) getSource();
		}
	}
}
